apiVersion: apps/v1
kind: Deployment
metadata:
   name: quarkas-helloworld

spec:
   replicas: 2
   selector:
       matchLabels:
             app: quarkas-helloworld


   template:
     metadata:
        labels:
          app: quarkas-helloworld

     spec:
       containers:
       - name: quarkas-helloworld
         image: acrimages2.azurecr.io/quarkus/hello-world-jvm:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
       imagePullSecrets:
       - name: secret-basic-auth
