apiVersion: v1
kind: Service
metadata:
   name: quarkas-helloworld
spec:
  selector:
    app: quarkas-helloworld

  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
   ## While running on production cluster, please use 'port: 80'
